version: '3.3'
services:
  db:
    container_name: nestjs-demo-db
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'nestjs_demo'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    command:
      - 'mysqld'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--skip-character-set-client-handshake'
      - '--default-authentication-plugin=mysql_native_password'
